### 게시글 저장하기
POST http://localhost:8080/board
Content-Type: application/json

{
"title": "title",
"content": "content",
"createdBy": "createdBy"
}

### 게시글 읽어오기
GET http://localhost:8080/board/1
Accept: application/json
