version: "3.8"

services:
  redis:
    container_name: playgroud-redis
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/redis-volume

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_SECURITY_DISABLED=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch#2025
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/opensearch-volume

volumes:
  redis-data:
  opensearch-data:
